// This file's content is autogenerated. It is used to keep track of the
// model schemas as they are in the database.

const schemas = {};

const migrations = { schemas } as const;

export default migrations;
