import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./_components/NavBar";
import { AppContextProvider } from "./_providers";
import "./_styles/globals.css";
import "./_styles/tiptap.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <NavBar />
          <main className="flex h-full min-h-[calc(100vh_-_80px)] flex-col">
            {children}
          </main>
        </AppContextProvider>
      </body>
    </html>
  );
}
